// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyC35RsRlUksyYzaAYFSTMkP88S98ios-eg',
//     appId: '1:556741497016:web:92fb3a009b2ba7dee8244d',
//     messagingSenderId: '556741497016',
//     projectId: 'abdisamed-27e8a',
//     authDomain: 'abdisamed-27e8a.firebaseapp.com',
//     databaseURL: 'https://abdisamed-27e8a-default-rtdb.firebaseio.com',
//     storageBucket: 'abdisamed-27e8a.appspot.com',
//     measurementId: 'G-WWS11VTM0S',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCbJuwQ_lkixx7O0Oop4fR-9O9WbzCTprQ',
//     appId: '1:556741497016:android:64a46adf30aa1b0ee8244d',
//     messagingSenderId: '556741497016',
//     projectId: 'abdisamed-27e8a',
//     databaseURL: 'https://abdisamed-27e8a-default-rtdb.firebaseio.com',
//     storageBucket: 'abdisamed-27e8a.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAYrbE-dNp9t6yza2fTAFLzk0feuctgfpw',
//     appId: '1:556741497016:ios:65996ff5ec419fdae8244d',
//     messagingSenderId: '556741497016',
//     projectId: 'abdisamed-27e8a',
//     databaseURL: 'https://abdisamed-27e8a-default-rtdb.firebaseio.com',
//     storageBucket: 'abdisamed-27e8a.appspot.com',
//     iosBundleId: 'com.example.abdisamed',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAYrbE-dNp9t6yza2fTAFLzk0feuctgfpw',
//     appId: '1:556741497016:ios:4f74d611deb8c658e8244d',
//     messagingSenderId: '556741497016',
//     projectId: 'abdisamed-27e8a',
//     databaseURL: 'https://abdisamed-27e8a-default-rtdb.firebaseio.com',
//     storageBucket: 'abdisamed-27e8a.appspot.com',
//     iosBundleId: 'com.example.abdisamed.RunnerTests',
//   );
// }
